version: "1"
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6380:6380

  location_api:

    restart: always
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 8080:8080
    depends_on:
      - redis