version: "3"

services:
  location_db:
    image: mysql
    environment:
      MYSQL_DATABASE: keyword_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    restart: on-failure

  location_redis:
    image: redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: on-failure

  location_api:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - location_redis
      - location_db
